-- show databases

-- drop database training

-- CREATE DATABASE TRAINING

-- USE TRAINING

-- SHOW TABLES

-- CREATE TABLE STUDENT(STU_ID INT,STU_NAME VARCHAR(30),STU_AGE INT)

-- show TABLES

-- DESCRIBE STUDENT

-- ALTER TABLE STUDENT ADD column STU_DEPART CHAR

-- CREATE TABLE EMPLOYEE(EMP_ID INT, EMP_SALARY decimal, EMP_AGE INT)

-- DESCRIBE EMPLOYEE

-- CREATE TABLE DEPARTMENT(DEPT_NAME INT, COLLEGE_NAME VARCHAR(10))

-- DESCRIBE DEPARTMENT

-- ALTER TABLE STUDENT ADD (EMAIL VARCHAR(30), CGPA INT(4))
 
-- DESC STUDENT

-- ALTER TABLE STUDENT DROP COLUMN STU_DEPART

-- DESC STUDENT

-- ALTER TABLE STUDENT MODIFY COLUMN STU_ID SMALLINT        

-- DESC STUDENT

-- DROP TABLE EMPLOYEE

-- DESC EMPLOYEE

-- DROP TABLE DEPARTMENT

-- DESC DEPARTMENT

-- DQl commands

-- SELECT * FROM STUDENT


use training

show tables


