use training
CREATE TABLE STUDENT(STU_ID INT PRIMARY KEY,STU_NAME VARCHAR(30) NOT NULL,AGE INT)
CREATE TABLE DEPARTMENT(DEPT_ID INT PRIMARY KEY,DEP_NAME VARCHAR(10),DP_ID INT NOT NULL,FOREIGN KEY(DP_ID) REFERENCES STUDENT(STU_ID))
INSERT INTO STUDENT VALUES(101,"SRINU",22)
INSERT INTO STUDENT VALUES(102,"GOPI",23)
SELECT * FROM STUDENT
INSERT INTO DEPARTMENT VALUES(121,"CSE",101)
INSERT INTO DEPARTMENT VALUES(122,"EEE",101)
INSERT INTO DEPARTMENT VALUES(123,"ECE",102)
