CREATE DATABASE AMAZON_CLON
USE AMAZON_CLON
CREATE TABLE USER_AC(ID INT,NAME VARCHAR(30),EMIAL_ID VARCHAR(50),MOBILE_NUMBER INT(10))
CREATE TABLE PRIME_AC(ID INT,NAME VARCHAR(30),EMIAL_ID VARCHAR(50),MOBILE_NUMBER INT(10),PRIME CHAR)
ALTER TABLE USER_AC ADD COLUMN PRIME CHAR
DESC USER_AC
DESC PRIME_AC
CREATE TABLE PRODUCT(PRO_ID INT,PRO_NAME VARCHAR(30),PRO_PRIZE BIGINT,PRO_DISCOUNT INT(10))
DESC PRODUCTsys_config
CREATE TABLE ORDERS(ORDER_ID INT,PRODUCT_NAME VARCHAR(30),FINAL_PRIZE INT,ADDRESS VARCHAR(30))
DESC ORDERS
