CREATE DATABASE FRUIT_SHOP

USE FRUIT_SHOP

CREATE TABLE FRUITSHOP(ID INT KEY AUTO_INCREMENT,NAME VARCHAR(30) NOT NULL,QUANTITY INT NOT NULL,COUNTER_NUMBER INT NOT NULL)

INSERT INTO FRUITSHOP(NAME,QUANTITY,COUNTER_NUMBER) VALUES("APPLE",12,108),("MANGO",20,101),("BANANA",18,106)

SELECT * FROM FRUITSHOP

CREATE TABLE APPLE(QUANTITY INT,COUNTER_NUMBER INT)

INSERT INTO APPLE(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUITSHOP WHERE NAME="APPLE"

SELECT * FROM APPLE

CREATE TABLE MANGO(QUANTITY INT,COUNTER_NUMBER INT)

INSERT INTO MANGO(QUANTITY,COUNTER_NUMBER) SELECT QUANTITY,COUNTER_NUMBER FROM FRUITSHOP WHERE NAME="MANGO"

SELECT * FROM MANGO


